apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.89.0
      helm:
        valueFiles:
          - $values/monitoring/vm-k8s-stack-values.yaml
    - repoURL: https://github.com/<nwanduka>/vm-project.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true